#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU

#---------------------------------#
#        environment init         #
#---------------------------------#
init:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

install:
- cmd: >-
    nuget install redis-64 -excludeversion

    redis-64\tools\redis-server.exe --service-install

    redis-64\tools\redis-server.exe --service-start

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
- cmd: nuget restore

build:
  project: StackExchange.Redis.Extensions.sln
  verbosity: minimal

#---------------------------------#
#       deploy configuration      #
#---------------------------------#
#deploy:
#  provider: NuGet
#  api_key:
#    secure: RiD8ByY1UxUnp+hyurAO3Ux8naiPVRMUX55HjjYe/ItiuKYk1PBGS9NgH80FbQ6C
#  artifact: /.*\.nupkg/
#  on:
#    branch: master
#    appveyor_repo_tag: true
	
#---------------------------------#
#          Notification           #
#---------------------------------#
notifications:
- provider: Slack
  auth_token:
    secure: Ka0JFHk0ML5+yq/Wy+1yqEZZtZKoeIxx7jHAihuwTaufIS0ADZc9NoxmwIn/zxckzfMdNdMq+1H54KypZM9PSA==
  channel: '#stackexchange-redis'
  template: >-
    <{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}>

    Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}:

    _{{commitMessage}}_
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
